### ISSUE TITLE
Interviews for Data Expert Persona

### ISSUE THREAD

**Issue by AubreySchiavone** [hackforla/access-the-data#185]
### **Overview**
Contact Data Experts to set up and conduct informational interviews

### **Action Items**

- [ ] Get access to Hack for LA's Access the Data email
- [ ] Contact 5 Data Experts from survey responses to schedule interviews
- [ ] Determine informational interview questions for each interviewee using survey responses to inform questions for each interviewee

### **Resources/Instructions**

- #163 
- [Data Expert Persona Screener Survey draft](https://docs.google.com/document/d/1qkKsD78xLcQ-iOE2uctssOInJS87HUCetleawxeiB9k/edit) & [Data Expert Screener Survey Form](https://docs.google.com/forms/d/1Y5EVtnXi3lCpklEnU1IMAxl9FyFKGnwmaJTyqcplK1A/edit).
- #176 
- [R.B. interview script](https://docs.google.com/document/d/1C-WHAU2J_CZpDmTmQPLc0BJ1gMz9x2gLe3gpBLPzM8w/edit), [R.B. interview video](https://drive.google.com/drive/folders/1Huind_V-ycMp5IjRUUJ-qdIsfhThC2Dq), [R.B. interview summary](https://docs.google.com/document/d/1Vs2MqqcyJmXMvOMNxfSGsDQ8AHbGp8LYRI0AMI9AtDU/edit)
- [User Interview Recordings and Transcripts](https://drive.google.com/drive/folders/14WQu2RwTbbjjSS8udqFZR2H6nZD5IqA8?usp=sharing)

**Comment by AubreySchiavone** [comment]
Data Expert Interviews as of 6/14/22

- M.M.: interviewed by Mariana 
- R.B.: Interviewed by Aubrey
- C.R. (already interviewed by Joyce and Sara as community activist, but he actually fits better into the Data Expert persona): Aubrey will reach out to and interview C.R. using Joyce’s previous email 
- H.D: Aubrey has reached out to H.D over email; will reach out over Slack as well
- H.K.: Aubrey will reach out to H.K. over email

**Comment by AubreySchiavone** [comment]
If anyone else would like to conduct one of the remaining three interviews (with C.R., H.D., or H.K.) that would be great.

**Comment by AubreySchiavone** [comment]
Interview questions posted in #176 but need to be individualized for each remaining interviewee (based on that interviewee's response to survey questions).

**Comment by Aparna1Gopal** [comment]
**Notes for HK Interview:** 
(Scheduled and conducted by @Aparna1Gopal) 

H.K Survey Responses 
https://docs.google.com/forms/d/1Y5EVtnXi3lCpklEnU1IMAxl9FyFKGnwmaJTyqcplK1A/edit#response=ACYDBNhhY3WJYjsr-m-94ux-47ixNTtWahof2byPJ3ju1Gb90PO5wJB-aQ1-MzzDLYPjuLc

Instructions from Slack: 
Hi Aparna, thanks so much. If you can schedule and conduct an interview with H.K. (Henry Kaplan) that would be great. The GitHub issue #185 has links to the interview script and an example interview I conducted with R.B. Once you have access to the Access the Data email account, you can use that to reach out to Henry. There is an email template and email signature from previous emails and posted to Drive. Once you have your interview scheduled you can invite any of the other researchers here to observe/note-take in the interview. 
[@Louis Chan](https://hackforla.slack.com/team/U03AEKRQKGF)
 has the link to Henry's survey responses, which you'll need to conduct your interview. I'd also be happy to Zoom with you briefly to talk about any of this if it's helpful.

[@Aubrey Schiavone](https://hackforla.slack.com/team/U039CS9JGTB)
 Many thanks! Your instructions are pretty clear. I have also reviewed all the resources (interview scripts etc.) attached to this issue and I am good to go! I will be in touch if I have any further questions.

**Comment by Aparna1Gopal** [comment]
**Notes for HK Interview:
(To be scheduled and conducted by @Aparna1Gopal)**

- Worked with PM to receive access to Access the Data gmail. 
- Set-up Calendly account for Access the Data for one-on-one/group interview scheduling. Can use Access the Data's Gmail to sign-in and use Calendly. 
- Contacted HK regarding setting up interview. Awaiting response

**Comment by Aparna1Gopal** [comment]
**Notes for HK Interview:
(To be scheduled and conducted by @Aparna1Gopal)**

- Contacted HK on Jun 23,2022 (5 days ago). Have not heard back yet. Will wait for a few more days on this one. 
- After which, will discuss with Data Expert research team and Research Lead on next steps.

**Comment by LouismChan** [comment]
Update on H.D. interview: got in touch with H.D over Slack.  He has agreed to look out for a new email from us next week to arrange for an interview.  Please send him another email to get the interview done.  Thanks. @Aparna1Gopal @AubreySchiavone @manosak @mmelovega

**Comment by Aparna1Gopal** [comment]
**Update on H.K. (Henry Kaplan) Interview:** 

- There has been no response from HK when contacted via ATD email, I have updated the UXR Lead and Data Expert team via Slack. 
- I will contact H.K again via email and also try Slack, to see if there is some momentum and response.

**Comment by Aparna1Gopal** [comment]
@LouismChan @mmelovega 

**Update on H.K. (Henry Kaplan) Interview:**

- Contacted research participant H.K via ATD email two times in the past three-four weeks and via Slack DM once (documented above) https://github.com/hackforla/access-the-data/issues/185#issuecomment-1172915766

- There has been no response thus far.

**Comment by Aparna1Gopal** [comment]
**Notes on H.K. Interview:** 
**Communication on Slack**

[From: Aparna G, To: Mariana M-V, Louis C]
Research Participant H.K's issue has been updated on GitHub. Based on the no response, can H.K.s issue be closed out? Thanks! 

[From: Mariana M-V, To:Aparna G]
Ok, let's move on.  Thank you Aparna!

Thus, closing out H.Ks issue

**Comment by mmelovega** [comment]
5 interviews completed and uploaded on [Google Drive](https://drive.google.com/drive/folders/14WQu2RwTbbjjSS8udqFZR2H6nZD5IqA8?usp=sharing)

**Comment by Aparna1Gopal** [comment]
**Notes**
Message from Slack: 

Aparna Gopal
 Hi At Mariana Melo-Vega! An FYI: Henry K has also responded to my Slack message, today. I had reached out during our user interview process. Could you please recommend on next steps and how best to proceed. I have already messaged him saying I am liaising with you now and will get back to him at the earliest. Thank You!

Mariana Melo-Vega
At Louis Chan: Henry K, who was originally scheduled to be interviewed as a Data Expert has reached back only now.  Do you think we need this extra interview? Initially I thought why not, but now I’m thinking that any extra interviews should be done as a set of 5 further along the project if we need it (and so there is no need for an interview with him now).  What do you think?

Louis Chan
Hi Aparna and Mariana,  It's not necessary for the data expert persona to have another interview.  But if you’d like, please go ahead and do the Henry K interview so that we can have another profile to work with, especially since this ATD project seems to have changed so that the data expert persona has become more important.


Aparna Gopal
At Mariana Melo-Vega
Based on the feedback above I will inform Henry K that we will have his details on file and circle back when we conduct the second round of data expert interviews.


Aparna G to Henry K
Hi H,
Thanks again for reaching out! I have discussed with our UXR Lead. The research team has already completed the first set of interviews and started iterating on the product. We would however, like your feedback and interview you when we start on the second round.
Could we please have your details on file and get back to you once we are ready to interview our next round of data experts? Please let me know what you think!
Thanks!
