### ISSUE TITLE
Recruitment/outreach of community advocate and expanding the database

### ISSUE THREAD

**Issue by bradyse** [hackforla/access-the-data#193]
### Overview

- We need to expand the community advocate recruitment to get people to complete the screener survey and/or sign-up for the (one-on-one, in-depth,qualitative) Interviews

- We need to recruit 5 research participants (community advocates) to assess the needs and pain points of this persona as we re-design the website based on CKAN

### Action Items
- [x] Based on the methodology, finalize on recruiting 5 research participants for first round of one-on-one user interviews (to develop on this community advocate persona)
- [x] Reach out to HfLA Citizen Engagement Project Managers
- [x] Ask PMs to provide us  contact info to add to our spreadsheet.
- [x] (Ongoing) Add NGO contacts to [Spreadsheet](https://docs.google.com/spreadsheets/d/1lE-0M2Fc9Njf71aG9wrlE5gXhyWh_hV1AnXEtKnu558/edit#gid=0)
~~- [ ] Recruit Research Participant 1~~
~~- [ ] Recruit Research Participant 2~~
~~- [ ] Recruit Research Participant 3~~
~~- [ ] Recruit Research Participant 4~~
~~- [ ] Recruit Research Participant 5~~
~~- [ ] Complete and finalize recruiting all 5 research participants and close issue~~

### Resources/Instructions
[Citizen Engagement Projects](https://www.hackforla.org/citizen-engagement)
[Community Activist Recruitment #184](https://github.com/hackforla/access-the-data/issues/184)
[Email Recruitment Message](https://docs.google.com/document/d/1IXu9rG2X-5Jx01zxp6MuSpZwQzJ09HYMvgdQGA-2hXQ/edit)

### Short Recruitment Message
**Are you a Community Activist?** Access the Data 📊 team is looking for **community-minded people** to interview and connect with to learn more about accessibility to city data. ✍🏿 This 2-minute [Screener Survey](https://docs.google.com/forms/d/e/1FAIpQLSd-lHSN9DLLzvpCtm05zKGkbHRQ2LoIvbZjJ9ilOcgV0-Xeqg/viewform) will be used to gain insights for building out an easy-to-navigate website of LA's open data resources. 🏙 Information from this screener will be used internally and anonymously. Thank you for your participation! 😎😄

**Comment by bradyse** [comment]
Notes from AJ:

Citizen Engagement
https://www.hackforla.org/citizen-engagement
[311 Data](https://www.hackforla.org/projects/311-data)
16.8: Broaden and strengthen the awareness and participation of City and local communities, especially those traditionally underserved and marginalized, in the institutions of local and global governance.
PM: [Eric Cho](https://hackforla.slack.com/team/U02E95SPK4N)
Research Lead:
[Access the Data](https://www.hackforla.org/projects/access-the-data)
16.8: Broaden and strengthen the awareness and participation of City and local communities, especially those traditionally underserved and marginalized, in the institutions of local and global governance.
PM:
Research Lead:
[Engage](https://www.hackforla.org/projects/engage)
16.8: Broaden and strengthen the awareness and participation of City and local communities, especially those traditionally underserved and marginalized, in the institutions of local and global governance.
PM: [Bryon Heart](https://hackforla.slack.com/team/U01GHT3EMNZ)
Research Lead:
[Lucky Parking](https://www.hackforla.org/projects/lucky-parking)
11.2: By 2030, provide access to safe, affordable, accessible and sustainable transport systems for all, improving road safety, notably by expanding public transport, with special attention to the needs of those in vulnerable situations, women, children, persons with disabilities and older persons.
PM: [Gordon Ruby](https://hackforla.slack.com/team/U02AJ61CSQP)
Research Lead:
[Open Community Survey](https://www.hackforla.org/projects/open-community-survey)
16.8: Broaden and strengthen the awareness and participation of City and local communities, especially those traditionally underserved and marginalized, in the institutions of local and global governance.
PM:
Research Lead:

**Comment by bradyse** [comment]
Responses:

- Eric Cho (311 Data) - _Planning an outreach campaign to onboard stakeholders for some alpha testing on the site, but that won’t be happening until after the summer_
- Byron Heart (Engage) - _No response_
- Greg Pawin (Lucky Parking) - _Project is in between PMs and they don't know enough about the project to provide contacts_
- Kalyani Raman (Open Community Survey) - _Said that Kalyani and Ambareen are PMs, asked Bonnie to provide contact info_

**Comment by bradyse** [comment]
- No leads with other HfLA Projects involved with Community Engagement. 
- 311 Data may have some additional information to share after the summer. 
- Reached out to EmpowerLA as part of the issue #184.

**Comment by mmelovega** [comment]
On the Research meeting (07/1272022) Sara, Aparna, Mariana and Hannah discussed the need to expand the spreadsheet with the NGO contacts to send the survey.

**Comment by bradyse** [comment]
@mxajPrice @lrchang2 

Could one of you please send out our [recruitment message](https://github.com/hackforla/access-the-data/issues/193#issue-1277544971) on Twitter like how you did with the Data Expert screener survey? See the resources/instructions for the text. Thank you!

**Comment by Aparna1Gopal** [comment]
**Working Notes** for @Aparna1Gopal 

Expand Community Activist Survey Recruitment – Extract names from Liberty Hill Project, Add name of Non-profit to the Spreadsheet- Email the contact person from ATD’s website with Screener Survey – Wait for response – Dual purpose of: Expanding the recruitment database and also outreach for potential interview participants

**Comment by lrchang2** [comment]
@bradyse the recruitment message is long for twitter and will have to be split into a chain of tweets if we want to keep all the content. consider revising to be shorter? 
![image](https://user-images.githubusercontent.com/10827101/178758984-fa4ec6de-f1b0-4dfb-b068-ee1286c22971.png)

**Comment by bradyse** [comment]
@lrchang2, how does this work for you? I shortened it to 280 characters. 

Are you a Community Activist? Access the Data team is looking for community-minded people to interview to learn more about accessibility to city data. This 2-min survey will be used to gain insights for building out an easy-to-navigate website. https://forms.gle/tUAAj53DhRKS6cMM6

**Comment by lrchang2** [comment]
@bradyse that works! do you want to add an @ to the Hack for LA twitter or a hashtag for better reach? We have 11 characters to do that 
![image](https://user-images.githubusercontent.com/10827101/178859931-4fb0edd6-a964-4e7c-913b-a1b820274c7b.png)

**Comment by bradyse** [comment]
@lrchang2 Yes, if it fits, then I would be in favor of that. Thank you so much!

**Comment by lrchang2** [comment]
here is the tweet https://twitter.com/accessthedata/status/1547382221681598464

**Comment by bradyse** [comment]
Updates

- Tweeted at EmpowerLA
- Sent a couple more emails from recruitment sheet

**Comment by bradyse** [comment]
Updates

- Sent recruitment message to Christine (from another HfLA project) for her to share with her colleagues.

**Comment by Aparna1Gopal** [comment]
Working Notes for @Aparna1Gopal 

Currently working on this recruitment and outreach https://github.com/hackforla/access-the-data/issues/193#issuecomment-1182819806

Will also reach out to ATD's PMs and UXR Lead to request for ATD's Facebook account, such that outreach could be carried out via FB in addition to the more traditional path of email to reach the grassroots community activists.

**Comment by Aparna1Gopal** [comment]
**Notes** 

- Updating Spreadsheet from the resources on this page https://www.libertyhill.org/organizations/
- Emailing each community activist non-profit from this group after updating spreadsheet

**Comment by Aparna1Gopal** [comment]
**Notes** 

Using the resources/non-profits identified in https://www.libertyhill.org/organizations/ for outreach
Also came across this website: polywork.com. Will also be using this for outreach in the upcoming weeks.

**Comment by hannahsgr** [comment]
- With the help of Matt and Mariana, rewrote the email template to make it more appealing and concise. 
- Compiled a list of community activists to reach out to. 
- Sent out emails.
- Trying a new approach: I directly ask community activists to sign up for an interview and take out the screener survey step. We have already established these people are community activists and if they're interested in using open source data for community advocacy they can sign up for a Zoom meeting using a Calendly link.

**Comment by mmelovega** [comment]
> * With the help of Matt and Mariana, rewrote the email template to make it more appealing and concise.
> * Compiled a list of community activists to reach out to.
> * Sent out emails.
> * Trying a new approach: I directly ask community activists to sign up for an interview and take out the screener survey step. We have already established these people are community activists and if they're interested in using open source data for community advocacy they can sign up for a Zoom meeting using a Calendly link.

**Comment by hannahsgr** [comment]
Email I'm currently using w/ Calendly link. 

Hello [NAME]!

I'm Hannah, a volunteer at Hack for LA, a brigade of Code for America. We want to talk to you about how you can use data to impact your community.

We are developing a free resource so that community activists like you can use open-source data in their advocacy. 

If you're interested in helping us develop a free resource to help people make data-driven decisions that impact their communities, please sign up [here](https://calendly.com/hannahsgr/30min?month=2022-08) for a 30 minute Zoom call. 

Thank you for your time, 
Hannah 
---------------------------------------------------------------------------------------------------------
More details:

🌐 This project is 100% open-source, transparent and community-led.
- Our workflow is available online at our [GitHub Repository](https://github.com/hackforla/access-the-data). 
- As we do our research, we will be adding our synthesized data onto the [Access the Data Wiki](https://github.com/hackforla/access-the-data/wiki).
- All names and personal information will be excluded from the published data.

Here is the [one-sheet](https://www.hackforla.org/assets/pdfs/Access-the-Data-One-Sheet.pdf) with more details on this project’s mission and goals.

**Comment by lrchang2** [comment]
@hannahsgr i should have caught this earlier. the one sheet you linked in the message is our old one. This is the new one: https://docs.google.com/document/d/17yzHv1Jx5Vf_QAHtgBZ0slU3no9BXneEB8GJscyKlpE/edit

**Comment by lrchang2** [comment]
I am going to email the moderators on a listserv to see if we can post there: 
- Data Ladies Alliance (DLA) 
    - 1500 people
    - This is a listserv for women, non-binary, trans, and non-conforming folks in progressive data and technology. We are committed to creating a safe space for our community to discuss working with progressive and political data and technology.

**Comment by Aparna1Gopal** [comment]
**Notes:** 

_Draft used on Calendly Link: (Image also attached)_ 

accessthedata project

Access the Data_User Interview
1 hr

Thank you for your interest in chatting with us regarding your community based work!

We look forward to deep diving into your community advocacy. And also understanding the role of data (if any) on your social impact.

More Information:
https://www.hackforla.org/projects/access-the-data.html
https://github.com/hackforla/access-the-data/

_Draft of Email used:_ 

Hello [NAME], 

Hope you are well! I am [NAME], a UX Researcher at Hack for LA, a brigade of Code for America. We want to talk to you about how you can use data to impact your work and community.

We are developing a free resource so that community advocates like you can use open-source data in their work and social impact. 

If you're interested in helping us develop a free resource to help people make data-driven decisions that impact their communities, please sign up [here](CALENDLY LINK) for a 30 minute Zoom call. 

Looking forward to hearing back from you,

Thank You!
[NAME]

---------------------------------------------------------------------------------------------------------
More details:

🌐 This project is 100% open-source, transparent and community-led.
Our workflow is available online at our [GitHub Repository](https://github.com/hackforla/access-the-data). 
As we do our research, we will be adding our synthesized data onto the [Access the Data Wiki](https://github.com/hackforla/access-the-data/wiki).
All names and personal information will be excluded from the published data.

Here is the [one-sheet](https://docs.google.com/document/d/17yzHv1Jx5Vf_QAHtgBZ0slU3no9BXneEB8GJscyKlpE/edit) with more details on this project’s mission and goals.

----------------------------------------------------------------------------------------------------

**Comment by Aparna1Gopal** [comment]
Notes

**Notes:** 

Using the resources/non-profits identified in https://www.libertyhill.org/organizations/ for outreach

Also came across this website: polywork.com. This seemed to have some members interested in community activism. Since I am not certain how this webpage works, will be doing some in-depth research on it. Will also be using this for outreach in the upcoming weeks if it works as a viable tool for research participant outreach.

Expanded database by adding resources

**Comment by Aparna1Gopal** [comment]
@lrchang2 Could you please Tweet our recruitment message to the people listed on our [Spreadsheet](https://docs.google.com/spreadsheets/d/1lE-0M2Fc9Njf71aG9wrlE5gXhyWh_hV1AnXEtKnu558/edit#gid=0) working for 'Alliance for Community Transit – Los Angeles'. They seemed pretty active on Twitter and their handles are documented in the spreadsheet. Many thanks!

**Comment by Aparna1Gopal** [comment]
**Notes:** 

UX Lead Mariana M and UXRs Hannah S and Aparna G worked collaboratively/ in real-time on this issue at todays's UXR meeting: 

- ATD Calendly account was set up
- We set up the Community Advocates User Interviews Calendly Event. Provided a wide timeframe for participants to sign up for interviews (7AM-9PM), Monday through Saturday. We were able to cover a wide time-frame due us being placed in different time-zones. 
- Updated the Calendly link on our Recruitment and Outreach Message (google dec)
- Mariana M posted our recruitment message on various Hack for LA Community of Practice channels 
- Mariana M will be posting our recruitment message on various Hack for LA Community of Practice channels as well

**Comment by Aparna1Gopal** [comment]
Notes: 

Sara B (ex-UXR at ATD Team) had reached out to Christine O (via email) from a different Hack for LA team to circulate our Recruitment message.  Christine O has responded asking if we are still recruiting. Since we are, the most recent and current recruitment/outreach message has been sent to be circulated amongst this contact's colleagues and network. 

_Recruitment Message:_ 
(a slightly different iteration, since this is going to be circulated by a contact) 

Our Recruitment Message

Hello!
Are you or someone in your network a community advocate who works with data? The Access the Data team is developing a free resource so that community advocates like you can use open-source data in their work.
If you’re interested in helping us out, please sign up [here](https://calendly.com/accessthedata/chatting-about-your-community-work) for a 15-20 minute Zoom call.

More details:

🌐 This project is 100% open-source, transparent and community-led.
Our workflow is available online at our [GitHub Repository](https://github.com/hackforla/access-the-data).
As we do our research, we will be adding our synthesized data onto the [Access the Data Wiki](https://github.com/hackforla/access-the-data/wiki).
All names and personal information will be excluded from the published data.

Here is the [one-sheet](https://docs.google.com/document/d/17yzHv1Jx5Vf_QAHtgBZ0slU3no9BXneEB8GJscyKlpE/edit) with more details on this project’s mission and goals.

**Comment by Aparna1Gopal** [comment]
**Notes:** 

_Twitter General Tweet messaging_ 

Hello! Are you or someone in your network a community advocate who works with data? Our team is developing a free resource so that community advocates like you can use open-source data in their work.
If you are interested in helping us out, we would love to talk to you! :wave::blush:

**Comment by Aparna1Gopal** [comment]
Notes: 
**Draft of Twitter Message - DM or @direct tweett:** 

Hi [NAME]! I am a UX Researcher at Hack for LA, a brigade of Code for America. We want to talk to you about how you can use data to impact your work and community.

We are developing a free resource so that community advocates like you can use open-source data in their work and social impact.

If you're interested in helping us develop a free resource to help people make data-driven decisions impacting their communities, please sign up [here](https://calendly.com/accessthedata/chatting-about-your-community-work) for a 30 minute Zoom call.

Looking forward to hearing back from you! 

More details:

🌐 This project is 100% open-source, transparent and community-led.
Our workflow is available online at our [GitHub Repository](https://github.com/hackforla/access-the-data).
As we do our research, we will be adding our synthesized data onto the [Access the Data Wiki](https://github.com/hackforla/access-the-data/wiki).
All names and personal information will be excluded from the published data.

Here is the [one-sheet](https://docs.google.com/document/d/17yzHv1Jx5Vf_QAHtgBZ0slU3no9BXneEB8GJscyKlpE/edit) with more details on this project’s mission and goals.

**Comment by Aparna1Gopal** [comment]
@lrchang2 **Update:** 

I did manage to log into AtD's Twitter account. The following were completed using AtD's Twitter account: 

- Tweeted general recruitment/outreach message on Tweeted
- Sent direct tweets to potential community advocates (research participants) 
- Also did some addditonal branding on AtD's Twitter profile, to make it more catchy and interesting to be able to grad more eyeballs as we recruit for research participants using Twitter (added a cover picture, completed details of AtD website, location, Bio etc.)

**Comment by Aparna1Gopal** [comment]
**Notes:** 

_For outreach and recruitment:_ 

- Followed https://www.libertyhill.org on Twitter for wider outreach of our recruitment message. 
- Signed up accessthedata@hackforla.org email ID to www.libertyhill.org's 'Join the Movement' to stay updated on the local community activism related activities taking place in the Los Angeles area.

**Comment by Aparna1Gopal** [comment]
**Notes:** 

@hannahsgr @Aparna1Gopal 

Based on the UX All-Team meeting on 09/21/2022 and feedback from PMs: the Action Items have been updated to reflect a start and end task to this issue, instead of keeping it as an ongoing, ever-expanding database issue (as it was initially planned)

**Comment by Aparna1Gopal** [comment]
**Notes:** 
From @Aparna1Gopal 

_Slack message communication:_ 
To Mariana M and Hannah S: We just got a community advocate sign-up on our Calendly for a user interview! The participant has signed up for September 22nd, so we need to scramble to prep for the interview! I am sending you both a private message with the details, for data privacy! CC: Lucy C, ajPrice, Bailey K

Update: The participant does not fit into the community advocate persona we are currently seeking. Based on feedback from UXR Lead and team, we have decided to pass on this one.

**Comment by Aparna1Gopal** [comment]
**Notes:** 
From @Aparna1Gopal 

_Slack message communication:_ 
To Mariana M and Hannah S: We just got a community advocate sign-up on our Calendly for a user interview! The participant has signed up for September 22nd, so we need to scramble to prep for the interview! I am sending you both a private message with the details, for data privacy! CC: Lucy C, ajPrice, Bailey K

Update: The participant does not fit into the community advocate persona we are currently seeking. Based on feedback from UXR Lead and team, we have decided to pass on this one.

**Comment by Aparna1Gopal** [comment]
**Notes:** 

- Outreach and recruitment email sent to 5 community advocates 

- Expanded and recorded the details of the community advocates in the database (spreadsheet)

**Comment by Aparna1Gopal** [comment]
**Notes:** 

Spoke to Sara B (UXR Lead TWE'22/ Internship Project, & ATD Alumni) regarding community network she may know in Nebraska. Will confirm with PMs during this week's team meeting and if this network (outside Los Angeles) is okayed, will sent our recruitment message to Sara B via email.

**Comment by Aparna1Gopal** [comment]
**Notes:** 

- Posted a new message on Twitter for community outreach. Message below. 
- Used hashtags this time to gain more traction. A short info regarding hashtag activism is also shared below (on the importance of using hashtags as an outreach/activism tool) 


[Hashtag Activism](https://en.wikipedia.org/wiki/Hashtag_activism) 




[Twitter Post](<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Hello! Our team is developing a free resource so that community advocates like you can use open-source data in their work. If you are interested in helping us out, we would love to talk to you! 👋😊<a href="https://twitter.com/hashtag/community?src=hash&amp;ref_src=twsrc%5Etfw">#community</a> <a href="https://twitter.com/hashtag/activism?src=hash&amp;ref_src=twsrc%5Etfw">#activism</a> <a href="https://twitter.com/hashtag/activist?src=hash&amp;ref_src=twsrc%5Etfw">#activist</a> <a href="https://twitter.com/hashtag/neighborhood?src=hash&amp;ref_src=twsrc%5Etfw">#neighborhood</a> <a href="https://twitter.com/hashtag/Communitymanager?src=hash&amp;ref_src=twsrc%5Etfw">#Communitymanager</a></p>&mdash; Access the Data (@accessthedata) <a href="https://twitter.com/accessthedata/status/1577179012753162242?ref_src=twsrc%5Etfw">October 4, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>)

Hello! Our team is developing a free resource so that community advocates like you can use open-source data in their work. If you are interested in helping us out, we would love to talk to you! 👋😊
[#community](https://twitter.com/hashtag/community?src=hashtag_click) [#activism](https://twitter.com/hashtag/activism?src=hashtag_click) [#activist](https://twitter.com/hashtag/activist?src=hashtag_click) [#neighborhood](https://twitter.com/hashtag/neighborhood?src=hashtag_click) [#Communitymanager](https://twitter.com/hashtag/Communitymanager?src=hashtag_click)

**Comment by Aparna1Gopal** [comment]
### Notes: 

**Based on meeting with PM Lucy C on October 13, 2022 this is being closed.**

- The project is currently pivoting in a new direction based on the current requirements of Access the Data. This includes ATD’s Website redesign based on CKAN incorporation and pivoting from the prior education modules model

- The personas (data expert and community activist) were developed during the education modules iteration of the project. The idea of creating a database of a research participant pool of data experts and community activists were also formulated during this stage of the project. 

- UX Researchers (prior & current) working on this issue have utilized multiple methods for outreach and recruiting research participants: including internal HfLA Slack, external Slack groups, Twitter, Email, cold calling etc. with links to Calendly for interview sign-up

- UX Researchers working on this issue have also expanded the database of potential community advocates/data experts over the course of 6+ months. 

- With the current restructuring of the team and the vision for the ATD website moving forward, LinkedIn poll is being used as a new strategy for participant recruitment. 

- This will also be used as a strategy to conduct new generative research to identify other persona types who will be potential users of ATD website & CKAN. 

- The important details from this issue will be transferred to ATD’s Wiki by the PMs.
