### ISSUE TITLE
Write New Copy for Volunteer Page

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#251]
### Overview
We need updated copy for the volunteer page of the website that follows our writing guide. 

### Action Items

- [x] Audit current text and consider new IA of the page
- [x] Create draft of copy for all sections of the volunteer page
    - [x] ATD team 
    - [x] Data Science Community of Practice 
- [x] Review copy with team for feedback and implement feedback
- [x] Pass off copy to designer to put into new volunteer page design in #196 

### Resources/Instructions
[figma
](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A27&t=WV5pqed63dwjuCZs-0)
[ATD copy guidelines](https://github.com/hackforla/access-the-data/wiki/Copy-Guide)

**Comment by mxajPrice** [comment]
please update your issue with the following info  if you have not already
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by lesUXW** [comment]
Hi @lrchang2 and @mxajPrice, here's my update so far:

- Progress: Audited AtD text. Drafting text based on the CURRENT Hi Fi Wireframes and IA.
- Blockers: Couldn't find new Volunteer Page on Figma, but found it on Issue #196 so using that as my example.
- Availability: Min. 6 hours
- ETA: 3-4 hours

- During the audit, found a possible error for "About Us" section. Is it "relay" or "rely"?

**Comment by lrchang2** [comment]
Based on [feedback from design of volunteer page](https://github.com/hackforla/access-the-data/issues/196#issuecomment-1423477179), copy should reflect the goals talked about. 

- Section 1: "Want to Volunteer" - be informational and let people know the different volunteer opportunities we provide
- ![image](https://user-images.githubusercontent.com/10827101/217691451-407fd7c2-7a12-428b-9db9-02dc19928909.png)
- Section 2: "Enter Your Information" - be actionable for people who know they want to volunteer/contribute 
- ![image](https://user-images.githubusercontent.com/10827101/217692452-2fe3b9bb-8f5b-426e-9604-070d47131ec6.png)

**Comment by lrchang2** [comment]
@lesUXW Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lesUXW** [comment]
Hi @lrchang2 and @mxajPrice, here's my update:

Progress: Sent UI text draft to designer. Need feedback from team on the text options.

Blockers: N/A

Availability: Min. 6 hours

ETA: By the end of this week after feedback from the team.

Pictures: 
![Group 308](https://user-images.githubusercontent.com/117793784/218892657-e51ce8c9-7f52-42e3-9155-9dcb11f6c5ef.png)

**Comment by lesUXW** [comment]
Hi @lrchang2 and @mxajPrice, here's my update:

Progress: Sent updated UI text draft to designer. Need final feedback from team on the text options.

Blockers: N/A

Availability: Min. 6 hours

ETA: N/A

Pictures: (below image is located in the Hi Fi Wireframes (Desktop)
![Feb  21, 2023 Option 3 after Feedback](https://user-images.githubusercontent.com/117793784/220468671-a9609278-254b-480b-bac6-8ec0909bc90c.png)

![Feb  21, 2023 Option 2 after Feedback (Data Science)](https://user-images.githubusercontent.com/117793784/220468695-4fd16bf5-585d-4c89-8e22-55c8ca09f832.png)

![Feb  21, 2023 Option 2 after Feedback (HfLa)](https://user-images.githubusercontent.com/117793784/220468707-3a9a77d8-e3c8-4631-95c2-f7cd06b65e08.png)

Thank you!

**Comment by lesUXW** [comment]
I saw @deepamohan22's mobile version, and due to the look, I decided to make a version with bullet points for easier legibility. Since it's bullet points, I was thinking it could either be only for mobile, or for both desktop and mobile for a consistent look.

![Feb  22, 2023 Volunteer Page UI Text Bullet Points 1](https://user-images.githubusercontent.com/117793784/220772153-639a4229-794c-4963-b073-bc0b324ffc88.png)

![Feb  22, 2023 Volunteer Page UI Text Bullet Points 2](https://user-images.githubusercontent.com/117793784/220772167-a682ead1-ea55-4863-a871-9c53a59b134d.png)

![Feb  22, 2023 Volunteer Page UI Text Bullet Points 3](https://user-images.githubusercontent.com/117793784/220772180-bc5c66b5-34f7-4dc2-ae73-b9603e74b94e.png)

Also since this is last minute and I'm not sure which time zone @deepamohan22 is at, and didn't want to risk the chance of waking her up if she's the opposite time zone, so I copied her desktop and mobile version, and replaced the text she made with the bullet points version so that we can see a version with that as well. It's located on Page 30. I hope this was ok for me to do.

Thank you!

**Comment by lrchang2** [comment]
![image](https://user-images.githubusercontent.com/10827101/220802447-b738798e-578d-41b3-a9a4-864d7cb3a78a.png)
team ideated on 3 versions of the bullet points as seen in the screen shot above. the team voted 100% for the first version with bolded first word

**Comment by lesUXW** [comment]
Hi @lrchang2 and @mxajPrice,

I've updated the UI text based on the feedback and poll from today's meeting, and notified @deepamohan22.

Here's the [link](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16&t=IILOsS9AFNmf1SXj-0) to see the update since images sent on here are blurry. It's the bottom purple rectangle and the white squares are the updated versions.

Thanks again!

**Comment by lrchang2** [comment]
@lesUXW this looks great! and it looks like deepa has implemented the new copy in the design, so i am closing out this issue.
