### ISSUE TITLE
311 Data Storyline Brainstorm

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#89]
### Overview
We are looking to anchor on a story that will be interesting to LA citizens leveraging available 311 data. Example storylines we have considered:

- Homeless encampments in Venice pre/post covid
- Illegal Dumping related to reduced frequency of Street sweeping pre/post covid

### Action Items
Each member of the Access the Data Workshop will provide 1-3 different ideas for us to consider in Wednesday's team meeting.

- [x] Shika 1-3 ideas
- [x] Malak 1-3 ideas
- [x] Mike 1-3 ideas

### Resources/Instructions
311data.org

**Comment by MalakH21** [comment]
@MalakH21 's ideas

1. Not sure if graffiti harbors some of the same sentiment as homeless encampments - but it seems like a good storyline to consider since the reporters here [cited the usage of 311](https://xtown.la/2021/02/23/graffiti-los-angeles-art/). Although you can only use the Alpha tool to go back as far in time as cited in the article, the map and data visualization tools lend themselves very well to understanding volume change. There could also be a local understanding of where a mural exists or street art and that could be used in conjunction with the tool to see how requests in that specific spot have changed over time vs. more "non-artistic" graffiti. 
2. Explore the interactions between [SSL] Single Streetlight and [MSL] Multiple Streetlight requests and particular intersects and traffic [collision data](https://data.lacity.org/Public-Safety/Traffic-Collision-Data-from-2010-to-Present/d5tf-ez2w) [and here](https://data.lacity.org/Public-Safety/Traffic-Accidents-by-date/2mzm-av8t) to see if there is any correlation - it might be difficult to pinpoint because it would involve digging into the _why_  of the accident, which may not be worth doing

**Comment by ShikaZzz** [comment]
Service request data from MyLA311 for 2015 - 2021
data source: [LA open data](https://data.lacity.org/browse?q=311+data&sortBy=relevance&page=1)

explore the data patterns and trends in:

- request source (call, mobile(iOS, Android))
- processing days (closed date - service created date)
- status (open, closed, canceled,out)
- seasonal (request # vs date per year)
....

with respect to request # per person/NC

so that we could see if there is anything interesting to make suggestion on e.g a specific request overwhelms in several NC's

**Comment by mcmorgan27** [comment]
**Background**
A bit of background/moodling to start:
1. I too am using the [MyLA311](https://data.lacity.org/City-Infrastructure-Service-Requests/MyLA311-Service-Request-Data-2021/97z7-y5bt) data set.
2. Thinking of 311 systems and [interoperability](http://eil.mie.utoronto.ca/wp-content/uploads/2015/06/nalchigar-jsc17.pdf) should be a long term goal, but probably beyond scope now.
3. Always a good place to help in thinking about [use cases](https://datasmart.ash.harvard.edu/news/article/how-can-data-and-analytics-be-used-to-enhance-city-operations-723)
4. One example of [system wide analytic thinking](https://gracepaet.com/2021/01/26/analysis-of-new-york-citys-311-service/).
5. Finally, one idea for a [data driven](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7347128/) application?  Could we building something like the [neighborhood indicators](https://www.healthaffairs.org/doi/pdf/10.1377/hlthaff.2014.0661) in SF?

I'm thinking of scoping base on different "user" types:
1.  Joe Citizen  - local resident
2. Suzy Small Biz owner - brings a commercial perspective to the problem/questions
3. NC board member/citizen volunteer
4. City level "planner" and "service agencies"

*I'm thinking about this from the data not the existing web app.  I'm starting to look at viability of these ideas in the app.*
 
**Use Cases/Storylines**

1.  Analyze at the Address Level - This question leads to an understanding of the blighted properties, properties that cause the most problems.  A generalization would be to look at reports by street (probably filtered by geographic NC area), ... This would primarily be focused at users 1, 2, 4
2. Analyze by request type + time - Get some averages for different services types. Target users 3, 4.
3. Analyze by "owner" (service org) + time - What are the patterns for each of the orgnanizations that service requests. Target users 3, 4.
4. Analyze by NC + use cases 2 and 3 - Combine basics geospatially?   Target users 3, 4.
5. Analyze with "other" NC information - This may be over the horizon but consider [foundation geometry](https://data.lacity.org/A-Well-Run-City/Neighborhoods/ykhe-zspy) combined with 1) [demographics](https://data.lacity.org/Community-Economic-Development/Census-Data-by-Neighborhood-Council/nwj3-ufba) for pop density; 2) or [osmnx](https://www.mdpi.com/2413-8851/3/1/28) by NC; or 3) or [zoning](https://data.lacity.org/Housing-and-Real-Estate/Zoning/rryw-49uv) geo's for commercial vs residential NC's; ...

These are some basic ideas.  I will look at the reference doc on 311 users from last night to see specifics of alignment.  I will put together more details for next monday.  Don't want to spend a lot of time if this is too far afield.

**Comment by snooravi** [comment]
Next steps: 
Chose your favorite topic and explore the datasets within or that would support to review on Wednesday with the team.

**Comment by MalakH21** [comment]
> @MalakH21 's ideas
> 
> 1. Not sure if graffiti harbors some of the same sentiment as homeless encampments - but it seems like a good storyline to consider since the reporters here [cited the usage of 311](https://xtown.la/2021/02/23/graffiti-los-angeles-art/). Although you can only use the Alpha tool to go back as far in time as cited in the article, the map and data visualization tools lend themselves very well to understanding volume change. There could also be a local understanding of where a mural exists or street art and that could be used in conjunction with the tool to see how requests in that specific spot have changed over time vs. more "non-artistic" graffiti.
> 2. Explore the interactions between [SSL] Single Streetlight and [MSL] Multiple Streetlight requests and particular intersects and traffic [collision data](https://data.lacity.org/Public-Safety/Traffic-Collision-Data-from-2010-to-Present/d5tf-ez2w) [and here](https://data.lacity.org/Public-Safety/Traffic-Accidents-by-date/2mzm-av8t) to see if there is any correlation - it might be difficult to pinpoint because it would involve digging into the _why_  of the accident, which may not be worth doing

relevant to #1 & #2 service request data - https://data.lacity.org/City-Infrastructure-Service-Requests/MyLA311-Service-Request-Data-2020/rq3b-xjk8

data source for #2 https://data.lacity.org/Public-Safety/Traffic-Collision-Data-from-2010-to-Present/d5tf-ez2w has codes for which types of collisions were caused by stop signs/street lights 

data sources for #1 more context on grafitti cleaning in LA http://laocb.org/programs/graffiti-abatement/

**Comment by snooravi** [comment]
Notes: 
- Link the service request type to the service organization (in the dataset).
- Identify neighborhood council (and neighboring councils)

 Final: 
- Moving forward with [@ShikaZzz ](https://github.com/hackforla/access-the-data/issues/89#issuecomment-960344503)

**Comment by ExperimentsInHonesty** [comment]
Re this post https://github.com/hackforla/access-the-data/issues/89#issuecomment-960305167

The definition of graffiti is unsanctioned painting on a surface

If you paint on a wall with the owner's permission is art
if you paint on the wall without the owner's permission, it's graffiti


> Not sure if graffiti harbors some of the same sentiment as homeless encampments - but it seems like a good storyline to consider since the reporters here cited the usage of 311. Although you can only use the Alpha tool to go back as far in time as cited in the article, the map and data visualization tools lend themselves very well to understanding volume change. There could also be a local understanding of where a mural exists or street art and that could be used in conjunction with the tool to see how requests in that specific spot have changed over time vs. more "non-artistic" graffiti.

Have you tried the Hack for LA 311 tool https://311-data.org?

> Explore the interactions between [SSL] Single Streetlight and [MSL] Multiple Streetlight requests and particular intersects and traffic collision data and here to see if there is any correlation - it might be difficult to pinpoint because it would involve digging into the why of the accident, which may not be worth doing

Have you reviewed the work Henry Kaplan did for Greater Wilshire  NC

**Comment by ExperimentsInHonesty** [comment]
@snooravi @mcmorgan27 @MalakH21 @ShikaZzz I think [Sarah ](https://github.com/hackforla/access-the-data/issues/89#issuecomment-965940144 )is indicting what I am about explicitly spell out, but I do want to leave the note on this issue for future team members.

After having read all the brainstorming here, I am appreciative of all the talent on this team.  

I think this is a great starting point
> @mcmorgan27 
> I'm thinking of scoping base on different "user" types:
> 1.  Joe Citizen  - local resident
> 2. Suzy Small Biz owner - brings a commercial perspective to the problem/questions
> 3. NC board member/citizen volunteer
> 4. City level "planner" and "service agencies"

> I'm thinking about this from the data not the existing web app. I'm starting to look at viability of these ideas in the app.
Data Analysis using the raw data from the portal is too high a level for the initial workshop. Our team will focus on building our workshop, which is how to use the 311-data.org tools and the Alpha Report Tool https://hackforla.github.io/311-report/

**Comment by snooravi** [comment]
Final outcome: 

We will focus on grafitti volume in LA over time in various neighborhoods.
